#! /usr/local/bin/python3

import random
import re
import sys

#input number of dice and type of dice, returns list of rolls
def roll_dice(quantity, sides):
    results = []
    for i in range(quantity):
        number = random.randint(1, sides)
        results.append(number)
    return results

#functional program begins
if len(sys.argv) < 2:
    print('Please input number of dice.')
    sys.exit(1)

dice_regexp = re.compile('^([1-9][0-9]*)d([1-9][0-9]*)$')
uint_regexp = re.compile('^[1-9][0-9]*$')

match = dice_regexp.match(sys.argv[1])
if match is None:
    print('Please format input in form #d#, e.g. 4d6')
    sys.exit(1)

quantity = int(match.group(1))
sides = int(match.group(2))

# results = []
# for i in range(quantity):
#     number = random.randint(1, sides)
#     results.append(number)

results = roll_dice(quantity, sides)

str_results = [str(r) for r in results]

#reminder: consolidate the following when you figure out how the fuck def actually works
#write: if sys.argv[1] is 'stats' roll 4d6 drop the lowest
if sys.argv
#delete when above is done!
elif len(sys.argv) < 3:
    total = sum(results)
    output = ' + '.join(str_results)
    output = output + ' = ' + str(total)
elif sys.argv[2] == 'min':
    total = min(results)
    output = ', '.join(str_results)
    output = output + ' : ' + str(total) + ' (min)'
elif sys.argv[2] == 'max':
    total = max(results)
    output = ', '.join(str_results)
    output = output + ' : ' + str(total) + ' (max)'
elif sys.argv[2] == '+':
    if len(sys.argv) < 4:
        print('Please input value to add.')
        sys.exit(1)
    elif uint_regexp.match(sys.argv[3]) is None:
        print('Please input integer to add.')
        sys.exit(1)
    total = sum(results)
    output = ' + '.join(str_results)
    output = output + ' = ' + str(total)
    print(output)
    output = str(total) + ' + ' + sys.argv[3] + ' = ' + str(total + int(sys.argv[3]))
elif sys.argv[2] == '-':
    if len(sys.argv) < 4:
        print('Please input value to subtract.')
        sys.exit(1)
    elif uint_regexp.match(sys.argv[3]) is None:
        print('Please input integer to subtract.')
        sys.exit(1)
    total = sum(results)
    output = ' + '.join(str_results)
    output = output + ' = ' + str(total)
    print(output)
    output = str(total) + ' - ' + sys.argv[3] + ' = ' + str(total - int(sys.argv[3]))
else:
    print('Invalid operation: ' + sys.argv[2])
    print('Valid operations: min, max, + value, - value, or no operation (sum).')
    sys.exit(1)

print(output)
